'use client';
import type { Metadata } from 'next';
import React from 'react';

import AppProviders from '@/providers/app-provider';
import { ThemeProvider } from '@/providers/theme-provider';

import './globals.css';
import Footer from '@/components/footer';

//-----------------------------------------------------------------------------------------------

// export const metadata: Metadata = {
//   title: 'Social Network',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="block relative bg-gray h-full w-full" suppressHydrationWarning={true}>
          <AppProviders>
            {children}
          </AppProviders>
      </body>
    </html>
  );
}